# Save this as 'Makefile' in the directory with your source
# Type 'make' to compile 'mysignal.c'
# Type 'make clean' to remove the executable and any *.o files
# Type 'info make' to get more information about how make works

all: mysignal

mysignal: mysignal.c
	gcc -o mysignal mysignal.c

clean:
	rm -f *.o mysignal
